markdown: kramdown
highlighter: pygments
permalink: /:year/:month/:day/:title.html
paginate: 6	
paginate_path: page/:num


# Build settings
# markdown: redcarpet
# redcarpet:
#     extensions: ["fenced_code_blocks", "tables", "highlight", "strikethrough"]

#SyntaxHihglighter config start

SyntaxHihglighter: false
shTheme: shThemeDefault # shThemeDefault  shThemeDjango  shThemeEclipse  shThemeEmacs  shThemeFadeToGrey  shThemeMidnight  shThemeRDark

#SyntaxHihglighter config end

blog:
    name: 爱博文                                         # 博客名称
    description: The time is passing                     # 博客描述
    title: 博雯个人博客                                  # 网页标题
    url: http://bowen.love                               # 博客地址
    duoshuo: bowenlove                                       # 多说ID 
    tongji:              # 百度统计ID
    clickiTongJi:					 # Clicki统计ID
    qiniu:                                               # 七牛云地址
author:
    name: 博雯                                          # 作者名称
    email: 240823537@qq.com                                # 邮箱地址
    weibo:                        # 微博地址
    github:                     # GitHub地址
    logo: /res/img/icon.jpg                              # logo地址
    douban:
        name:                                            # 豆瓣地址名称
        key:                                             # 豆瓣API Key